### ISSUE TITLE
[feature request] include a sin() that accept degrees instead of radians

### ISSUE THREAD

**Issue by microcai** [MikeLankamp/fpm#59]
since we use "fixed point", then we are much eagger to avoid "pi" in our program code.

**Comment by MikeLankamp** [comment]
Hi @microcai, thank you for using `fpm` and participating in its development. However, I'm afraid I have to decline this request for two reasons:
1. `fpm` aims to mirror the C++ standard library, which does not offer similar functionality.
2. even if a version of `sin` would accept degrees, the input, internal calculations, and result, would still be fractional. The only thing you save is one operation that multiplies with a factor `180/PI`, and that's just because the input in your domain happens to be in degrees.

Note that `fpm` also has a constexpr `pi` value in fixed-point format, ready to be used. I refer you to the documentation.

If you still strongly feel about this, please re-open this issue with a good rationale.

**Comment by Klummel69** [comment]
Hi @microcai,
Short addition, I am working on an optimized version of the functions sin(),cos(),tan() - hope to finish the whole thing in the next weeks.

I had thought about creating a version in degrees instead of radians,
because the finite precision of the number Pi in fixpoint can lead to calculation errors, especially with very large angles. The angle calculation in degrees has advantages here.

If necessary, I will provide additional versions.

**Comment by microcai** [comment]
@Klummel69  wow, what a good news!
